name: klasflow
description: Flutter에서 KLAS를 사용하기 위한 고수준 Dart SDK
version: 1.0.0
homepage: https://github.com/your-org/klasflow
repository: https://github.com/your-org/klasflow
issue_tracker: https://github.com/your-org/klasflow/issues
topics:
  - flutter
  - dart
  - sdk
  - klas

environment:
  sdk: ^3.10.8

dependencies:
  encrypt: ^5.0.3
  html: ^0.15.6
  http: ^1.5.0
  pointycastle: ^3.9.1

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.25.6
