name: klasflow
description: High-level Dart SDK for KLAS with user and course domain APIs
version: 1.2.0
homepage: https://github.com/jungwuk-ryu/klas-flow
repository: https://github.com/jungwuk-ryu/klas-flow
issue_tracker: https://github.com/jungwuk-ryu/klas-flow/issues
topics:
  - flutter
  - dart
  - sdk
  - klas

environment:
  sdk: ^3.10.8

dependencies:
  encrypt: ^5.0.3
  html: ^0.15.6
  http: ^1.6.0
  pointycastle: ^3.9.1

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.25.6
