import 'dart:io';

import 'package:klasflow/src/api/readonly_api.dart';

const _groupSuffixOverrides = <String, String>{
  'learning': 'Learning',
  'boardSurvey': 'BoardSurvey',
  'frame': 'Frame',
  'loginSession': 'LoginSession',
  'session': 'Session',
  'enrollment': 'Enrollment',
  'eclass': 'EClass',
  'attendance': 'Attendance',
  'file': 'File',
  'academic': 'Academic',
  'studentRecord': 'StudentRecord',
};

void main() {
  final grouped = <String, List<KlasEndpointSpec>>{};

  for (final entry in KlasEndpointCatalog.byId.entries) {
    final id = entry.key;
    final separator = id.indexOf('.');
    final group = separator == -1 ? 'misc' : id.substring(0, separator);

    grouped.putIfAbsent(group, () => <KlasEndpointSpec>[]).add(entry.value);
  }

  final buffer = StringBuffer()
    ..writeln('// ignore_for_file: non_constant_identifier_names')
    ..writeln("import '../models/file_payload.dart';")
    ..writeln("import 'readonly_api.dart';")
    ..writeln()
    ..writeln('/// Generated from `KlasEndpointCatalog.byId`.')
    ..writeln('/// DO NOT edit this file manually.')
    ..writeln('final class KlasTypedEndpoints {')
    ..writeln('  final KlasReadOnlyApi _api;')
    ..writeln();

  for (final group in grouped.keys) {
    final fieldName = _fieldName(group);
    final className = _groupClassName(group);
    buffer.writeln('  late final $className $fieldName = $className(_api);');
  }

  buffer
    ..writeln()
    ..writeln('  KlasTypedEndpoints(this._api);')
    ..writeln('}')
    ..writeln();

  for (final entry in grouped.entries) {
    final group = entry.key;
    final specs = entry.value;
    final className = _groupClassName(group);

    buffer
      ..writeln('final class $className {')
      ..writeln('  final KlasReadOnlyApi _api;')
      ..writeln('  $className(this._api);')
      ..writeln();

    for (final spec in specs) {
      final methodName = _methodName(spec.id);
      final returnType = _returnType(spec.responseType);
      final delegateMethod = _delegateMethod(spec.responseType);
      final isBinary = spec.responseType == KlasEndpointResponseType.binary;

      if (isBinary) {
        buffer
          ..writeln("  /// `${spec.id}` (${spec.path})")
          ..writeln('  Future<$returnType> $methodName({')
          ..writeln('    Map<String, String>? pathParams,')
          ..writeln('    Map<String, String>? query,')
          ..writeln('  }) {')
          ..writeln('    return _api.$delegateMethod(')
          ..writeln("      '${spec.id}',")
          ..writeln('      pathParams: pathParams,')
          ..writeln('      query: query,')
          ..writeln('    );')
          ..writeln('  }')
          ..writeln();
      } else {
        buffer
          ..writeln("  /// `${spec.id}` (${spec.path})")
          ..writeln('  Future<$returnType> $methodName({')
          ..writeln('    Map<String, dynamic>? payload,')
          ..writeln('    Map<String, String>? pathParams,')
          ..writeln('    Map<String, String>? query,')
          ..writeln('    bool? includeContext,')
          ..writeln('  }) {')
          ..writeln('    return _api.$delegateMethod(')
          ..writeln("      '${spec.id}',")
          ..writeln('      payload: payload,')
          ..writeln('      pathParams: pathParams,')
          ..writeln('      query: query,')
          ..writeln('      includeContext: includeContext,')
          ..writeln('    );')
          ..writeln('  }')
          ..writeln();
      }
    }

    buffer
      ..writeln('}')
      ..writeln();
  }

  final output = File('lib/src/api/typed_endpoints.dart');
  output.writeAsStringSync(buffer.toString());
  stdout.writeln('Generated: ${output.path}');
}

String _fieldName(String group) {
  final words = _splitWords(group);
  if (words.isEmpty) {
    return group;
  }

  final head = words.first.toLowerCase();
  final tail = words.skip(1).map(_capitalize).join();
  return '$head$tail';
}

String _groupClassName(String group) {
  final override = _groupSuffixOverrides[group];
  if (override != null) {
    return 'Klas${override}Endpoints';
  }
  return 'Klas${_splitWords(group).map(_capitalize).join()}Endpoints';
}

String _methodName(String endpointId) {
  final separator = endpointId.indexOf('.');
  if (separator == -1 || separator == endpointId.length - 1) {
    return endpointId;
  }
  return endpointId.substring(separator + 1);
}

String _returnType(KlasEndpointResponseType type) {
  switch (type) {
    case KlasEndpointResponseType.jsonObject:
      return 'Map<String, dynamic>';
    case KlasEndpointResponseType.jsonArray:
      return 'List<dynamic>';
    case KlasEndpointResponseType.jsonScalar:
      return 'dynamic';
    case KlasEndpointResponseType.text:
      return 'String';
    case KlasEndpointResponseType.binary:
      return 'FilePayload';
  }
}

String _delegateMethod(KlasEndpointResponseType type) {
  switch (type) {
    case KlasEndpointResponseType.jsonObject:
      return 'callObject';
    case KlasEndpointResponseType.jsonArray:
      return 'callArray';
    case KlasEndpointResponseType.jsonScalar:
      return 'call';
    case KlasEndpointResponseType.text:
      return 'callText';
    case KlasEndpointResponseType.binary:
      return 'callBinary';
  }
}

List<String> _splitWords(String value) {
  final normalized = value.replaceAll(RegExp(r'[^a-zA-Z0-9]'), ' ');
  final words = <String>[];

  for (final raw in normalized.split(' ')) {
    if (raw.isEmpty) {
      continue;
    }
    final parts = raw.split(RegExp(r'(?=[A-Z])'));
    for (final part in parts) {
      if (part.isNotEmpty) {
        words.add(part.toLowerCase());
      }
    }
  }
  return words;
}

String _capitalize(String value) {
  if (value.isEmpty) {
    return value;
  }
  return '${value[0].toUpperCase()}${value.substring(1)}';
}
