// ignore_for_file: non_constant_identifier_names
import '../models/file_payload.dart';
import 'readonly_api.dart';

/// Generated from `KlasEndpointCatalog.byId`.
/// DO NOT edit this file manually.
final class KlasTypedEndpoints {
  final KlasReadOnlyApi _api;

  late final KlasLearningEndpoints learning = KlasLearningEndpoints(_api);
  late final KlasBoardSurveyEndpoints boardSurvey = KlasBoardSurveyEndpoints(_api);
  late final KlasFrameEndpoints frame = KlasFrameEndpoints(_api);
  late final KlasLoginSessionEndpoints loginSession = KlasLoginSessionEndpoints(_api);
  late final KlasSessionEndpoints session = KlasSessionEndpoints(_api);
  late final KlasEnrollmentEndpoints enrollment = KlasEnrollmentEndpoints(_api);
  late final KlasEClassEndpoints eclass = KlasEClassEndpoints(_api);
  late final KlasAttendanceEndpoints attendance = KlasAttendanceEndpoints(_api);
  late final KlasFileEndpoints file = KlasFileEndpoints(_api);
  late final KlasAcademicEndpoints academic = KlasAcademicEndpoints(_api);
  late final KlasStudentRecordEndpoints studentRecord = KlasStudentRecordEndpoints(_api);

  KlasTypedEndpoints(this._api);
}

final class KlasLearningEndpoints {
  final KlasReadOnlyApi _api;
  KlasLearningEndpoints(this._api);

  /// `learning.anytmQuizStdList` (/std/lis/evltn/AnytmQuizStdList.do)
  Future<List<dynamic>> anytmQuizStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.anytmQuizStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.dscsnStdList` (/std/lis/evltn/DscsnStdList.do)
  Future<List<dynamic>> dscsnStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.dscsnStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.lctrumHomeStdInfo` (/std/lis/evltn/LctrumHomeStdInfo.do)
  Future<Map<String, dynamic>> lctrumHomeStdInfo({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'learning.lctrumHomeStdInfo',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.lrnSttusStdAtendList` (/std/lis/evltn/LrnSttusStdAtendList.do)
  Future<List<dynamic>> lrnSttusStdAtendList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.lrnSttusStdAtendList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.lrnSttusStdAtendListSub` (/std/lis/evltn/LrnSttusStdAtendListSub.do)
  Future<List<dynamic>> lrnSttusStdAtendListSub({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.lrnSttusStdAtendListSub',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.lrnSttusStdDscsnList` (/std/lis/evltn/LrnSttusStdDscsnList.do)
  Future<List<dynamic>> lrnSttusStdDscsnList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.lrnSttusStdDscsnList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.lrnSttusStdOne` (/std/lis/evltn/LrnSttusStdOne.do)
  Future<Map<String, dynamic>> lrnSttusStdOne({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'learning.lrnSttusStdOne',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.lrnSttusStdRtprgsList` (/std/lis/evltn/LrnSttusStdRtprgsList.do)
  Future<List<dynamic>> lrnSttusStdRtprgsList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.lrnSttusStdRtprgsList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.lrnSttusStdTaskList` (/std/lis/evltn/LrnSttusStdTaskList.do)
  Future<List<dynamic>> lrnSttusStdTaskList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.lrnSttusStdTaskList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.lrnSttusStdTeamPrjctList` (/std/lis/evltn/LrnSttusStdTeamPrjctList.do)
  Future<List<dynamic>> lrnSttusStdTeamPrjctList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.lrnSttusStdTeamPrjctList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.lrnSttusStdTestAnQuizList` (/std/lis/evltn/LrnSttusStdTestAnQuizList.do)
  Future<List<dynamic>> lrnSttusStdTestAnQuizList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.lrnSttusStdTestAnQuizList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.onlineTestStdList` (/std/lis/evltn/OnlineTestStdList.do)
  Future<List<dynamic>> onlineTestStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.onlineTestStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.selectOnlineCntntsStdList` (/std/lis/evltn/SelectOnlineCntntsStdList.do)
  Future<List<dynamic>> selectOnlineCntntsStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.selectOnlineCntntsStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `learning.taskStdList` (/std/lis/evltn/TaskStdList.do)
  Future<List<dynamic>> taskStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'learning.taskStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasBoardSurveyEndpoints {
  final KlasReadOnlyApi _api;
  KlasBoardSurveyEndpoints(this._api);

  /// `boardSurvey.boardStdList_6972896b` (/std/lis/sport/6972896bfe72408eb72926780e85d041/BoardStdList.do)
  Future<Map<String, dynamic>> boardStdList_6972896b({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'boardSurvey.boardStdList_6972896b',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `boardSurvey.boardStdView_6972896b` (/std/lis/sport/6972896bfe72408eb72926780e85d041/BoardStdView.do)
  Future<Map<String, dynamic>> boardStdView_6972896b({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'boardSurvey.boardStdView_6972896b',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `boardSurvey.boardStdList_d052b8f8` (/std/lis/sport/d052b8f845784c639f036b102fdc3023/BoardStdList.do)
  Future<Map<String, dynamic>> boardStdList_d052b8f8({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'boardSurvey.boardStdList_d052b8f8',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `boardSurvey.boardStdView_d052b8f8` (/std/lis/sport/d052b8f845784c639f036b102fdc3023/BoardStdView.do)
  Future<Map<String, dynamic>> boardStdView_d052b8f8({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'boardSurvey.boardStdView_d052b8f8',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `boardSurvey.boardViewStdPage_d052b8f8` (/std/lis/sport/d052b8f845784c639f036b102fdc3023/BoardViewStdPage.do)
  Future<String> boardViewStdPage_d052b8f8({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callText(
      'boardSurvey.boardViewStdPage_d052b8f8',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `boardSurvey.qustnrStdList` (/std/lis/sport/QustnrStdList.do)
  Future<List<dynamic>> qustnrStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'boardSurvey.qustnrStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `boardSurvey.qustnrStdPage` (/std/lis/sport/QustnrStdPage.do)
  Future<String> qustnrStdPage({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callText(
      'boardSurvey.qustnrStdPage',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasFrameEndpoints {
  final KlasReadOnlyApi _api;
  KlasFrameEndpoints(this._api);

  /// `frame.gyojikExamCheck` (/std/cmn/frame/GyojikExamCheck.do)
  Future<Map<String, dynamic>> gyojikExamCheck({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'frame.gyojikExamCheck',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `frame.klasStop` (/std/cmn/frame/KlasStop.do)
  Future<String> klasStop({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callText(
      'frame.klasStop',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `frame.lctrumSchdulInfo` (/std/cmn/frame/LctrumSchdulInfo.do)
  Future<dynamic> lctrumSchdulInfo({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.call(
      'frame.lctrumSchdulInfo',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `frame.schdulStdList` (/std/cmn/frame/SchdulStdList.do)
  Future<Map<String, dynamic>> schdulStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'frame.schdulStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `frame.stdHome` (/std/cmn/frame/StdHome.do)
  Future<Map<String, dynamic>> stdHome({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'frame.stdHome',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `frame.yearhakgiAtnlcSbjectList` (/std/cmn/frame/YearhakgiAtnlcSbjectList.do)
  Future<List<dynamic>> yearhakgiAtnlcSbjectList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'frame.yearhakgiAtnlcSbjectList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasLoginSessionEndpoints {
  final KlasReadOnlyApi _api;
  KlasLoginSessionEndpoints(this._api);

  /// `loginSession.captchaImg` (/usr/cmn/login/captchaImg.do)
  Future<FilePayload> captchaImg({
    Map<String, String>? pathParams,
    Map<String, String>? query,
  }) {
    return _api.callBinary(
      'loginSession.captchaImg',
      pathParams: pathParams,
      query: query,
    );
  }

  /// `loginSession.loginCaptcha` (/usr/cmn/login/LoginCaptcha.do)
  Future<dynamic> loginCaptcha({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.call(
      'loginSession.loginCaptcha',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `loginSession.loginConfirm` (/usr/cmn/login/LoginConfirm.do)
  Future<Map<String, dynamic>> loginConfirm({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'loginSession.loginConfirm',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `loginSession.loginSecurity` (/usr/cmn/login/LoginSecurity.do)
  Future<Map<String, dynamic>> loginSecurity({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'loginSession.loginSecurity',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `loginSession.updateSession` (/usr/cmn/login/UpdateSession.do)
  Future<Map<String, dynamic>> updateSession({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'loginSession.updateSession',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasSessionEndpoints {
  final KlasReadOnlyApi _api;
  KlasSessionEndpoints(this._api);

  /// `session.info` (/api/v1/session/info)
  Future<Map<String, dynamic>> info({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'session.info',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasEnrollmentEndpoints {
  final KlasReadOnlyApi _api;
  KlasEnrollmentEndpoints(this._api);

  /// `enrollment.atnlcYearList` (/std/cps/atnlc/AtnlcYearList.do)
  Future<List<dynamic>> atnlcYearList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'enrollment.atnlcYearList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `enrollment.cmmnGamokList` (/std/cps/atnlc/CmmnGamokList.do)
  Future<List<dynamic>> cmmnGamokList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'enrollment.cmmnGamokList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `enrollment.cmmnHakgwaList` (/std/cps/atnlc/CmmnHakgwaList.do)
  Future<List<dynamic>> cmmnHakgwaList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'enrollment.cmmnHakgwaList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `enrollment.lctrePlanStopFlag` (/std/cps/atnlc/LctrePlanStopFlag.do)
  Future<String> lctrePlanStopFlag({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callText(
      'enrollment.lctrePlanStopFlag',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `enrollment.timetableStdList` (/std/cps/atnlc/TimetableStdList.do)
  Future<List<dynamic>> timetableStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'enrollment.timetableStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasEClassEndpoints {
  final KlasReadOnlyApi _api;
  KlasEClassEndpoints(this._api);

  /// `eclass.eClassStdList` (/std/lis/lctre/EClassStdList.do)
  Future<List<dynamic>> eClassStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'eclass.eClassStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasAttendanceEndpoints {
  final KlasReadOnlyApi _api;
  KlasAttendanceEndpoints(this._api);

  /// `attendance.kwAttendStdGwakmokList` (/std/ads/admst/KwAttendStdGwakmokList.do)
  Future<List<dynamic>> kwAttendStdGwakmokList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'attendance.kwAttendStdGwakmokList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `attendance.mySchdulMonthList` (/std/ads/admst/MySchdulMonthList.do)
  Future<List<dynamic>> mySchdulMonthList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'attendance.mySchdulMonthList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `attendance.mySchdulMonthTableList` (/std/ads/admst/MySchdulMonthTableList.do)
  Future<List<dynamic>> mySchdulMonthTableList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'attendance.mySchdulMonthTableList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasFileEndpoints {
  final KlasReadOnlyApi _api;
  KlasFileEndpoints(this._api);

  /// `file.downloadFile` (/common/file/DownloadFile/{attachId}/{fileSn})
  Future<FilePayload> downloadFile({
    Map<String, String>? pathParams,
    Map<String, String>? query,
  }) {
    return _api.callBinary(
      'file.downloadFile',
      pathParams: pathParams,
      query: query,
    );
  }

  /// `file.uploadFileList` (/common/file/UploadFileList.do)
  Future<List<dynamic>> uploadFileList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'file.uploadFileList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasAcademicEndpoints {
  final KlasReadOnlyApi _api;
  KlasAcademicEndpoints(this._api);

  /// `academic.atnlcScreCheckTerm` (/std/cps/inqire/AtnlcScreCheckTerm.do)
  Future<Map<String, dynamic>> atnlcScreCheckTerm({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'academic.atnlcScreCheckTerm',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.atnlcScreHakjukInfo` (/std/cps/inqire/AtnlcScreHakjukInfo.do)
  Future<Map<String, dynamic>> atnlcScreHakjukInfo({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'academic.atnlcScreHakjukInfo',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.atnlcScreProgramGubun` (/std/cps/inqire/AtnlcScreProgramGubun.do)
  Future<Map<String, dynamic>> atnlcScreProgramGubun({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'academic.atnlcScreProgramGubun',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.atnlcScreSugangOpt` (/std/cps/inqire/AtnlcScreSugangOpt.do)
  Future<dynamic> atnlcScreSugangOpt({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.call(
      'academic.atnlcScreSugangOpt',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.atnlcScreSungjukInfo` (/std/cps/inqire/AtnlcScreSungjukInfo.do)
  Future<List<dynamic>> atnlcScreSungjukInfo({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.atnlcScreSungjukInfo',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.atnlcScreSungjukTot` (/std/cps/inqire/AtnlcScreSungjukTot.do)
  Future<Map<String, dynamic>> atnlcScreSungjukTot({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'academic.atnlcScreSungjukTot',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.delAppliedList` (/std/cps/inqire/DelAppliedList.do)
  Future<List<dynamic>> delAppliedList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.delAppliedList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.delHakjukInfo` (/std/cps/inqire/DelHakjukInfo.do)
  Future<Map<String, dynamic>> delHakjukInfo({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'academic.delHakjukInfo',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.delSungjukStdList` (/std/cps/inqire/DelSungjukStdList.do)
  Future<List<dynamic>> delSungjukStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.delSungjukStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.gyoyangIsuInfo` (/std/cps/inqire/GyoyangIsuInfo.do)
  Future<Map<String, dynamic>> gyoyangIsuInfo({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'academic.gyoyangIsuInfo',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.individualPortfolioStdList` (/std/cps/inqire/IndividualPortfolioStdList.do)
  Future<List<dynamic>> individualPortfolioStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.individualPortfolioStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.janghakHistoryStdList` (/std/cps/inqire/JanghakHistoryStdList.do)
  Future<List<dynamic>> janghakHistoryStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.janghakHistoryStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.janghakStdList` (/std/cps/inqire/JanghakStdList.do)
  Future<List<dynamic>> janghakStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.janghakStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.lctreEvlResultGwamokList` (/std/cps/inqire/LctreEvlResultGwamokList.do)
  Future<List<dynamic>> lctreEvlResultGwamokList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.lctreEvlResultGwamokList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.lctreEvlResultSetHakgwa` (/std/cps/inqire/LctreEvlResultSetHakgwa.do)
  Future<List<dynamic>> lctreEvlResultSetHakgwa({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.lctreEvlResultSetHakgwa',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.standStdList` (/std/cps/inqire/StandStdList.do)
  Future<List<dynamic>> standStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.standStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.toeicInfoStd` (/std/cps/inqire/ToeicInfoStd.do)
  Future<List<dynamic>> toeicInfoStd({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.toeicInfoStd',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.toeicLevelInfo` (/std/cps/inqire/ToeicLevelInfo.do)
  Future<String> toeicLevelInfo({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callText(
      'academic.toeicLevelInfo',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `academic.toeicStdList` (/std/cps/inqire/ToeicStdList.do)
  Future<List<dynamic>> toeicStdList({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callArray(
      'academic.toeicStdList',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

final class KlasStudentRecordEndpoints {
  final KlasReadOnlyApi _api;
  KlasStudentRecordEndpoints(this._api);

  /// `studentRecord.tmpabssklGetHakjuk` (/std/hak/hakjuk/TmpabssklGetHakjuk.do)
  Future<Map<String, dynamic>> tmpabssklGetHakjuk({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'studentRecord.tmpabssklGetHakjuk',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

  /// `studentRecord.tmpabssklStatu` (/std/hak/hakjuk/TmpabssklStatu.do)
  Future<Map<String, dynamic>> tmpabssklStatu({
    Map<String, dynamic>? payload,
    Map<String, String>? pathParams,
    Map<String, String>? query,
    bool? includeContext,
  }) {
    return _api.callObject(
      'studentRecord.tmpabssklStatu',
      payload: payload,
      pathParams: pathParams,
      query: query,
      includeContext: includeContext,
    );
  }

}

